language:
  - node_js

node_js:
  - "8.10.0"

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "memory-cloud"

services:
  - mysql
  - mongodb
  - redis-server

install:
  - npm install

script:
  - npm run lint
  - npm run travis-test
  - sonar-scanner

after_success:
  - "curl -H \"Content-Type: application/json\" --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/rafaelnds/memory-cloud/trigger/$DOCKER_TOKEN/"
