language:
  - node_js

node_js:
  - "8.10.0"

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "memory-cloud"

services:
  - mysql

install:
  - npm install

script:
  - npm run travis-test
  - sonar-scanner
