version: '3.3'

services:
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  mongodb:
    image: mongo:3.4
    volumes:
      - db_data:/data/db
    restart: always
    ports:
      - 27017:27017
  redis:
    image: redis:4.0.9
    ports:
      - 6379:6379
    restart: always
#  memorycloud:
#    build: ./
#    depends_on:
#     - "db"
#    restart: always
#    environment:
#      MYSQL_HOST: db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_DATABASE: memorycloud
#      MONGODB_URI: mongodb://mongodb:27017/memorycloud

volumes:
  db_data:
