version: '3.3'

services:
  db:
    image: mysql:5.6
    ports:
    - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  memorycloud:
    build: ./
    depends_on:
     - "db"
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: memorycloud

volumes:
  db_data: